// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

type Article struct {
	ID       int64
	SourceID int64
	Title    string
	Url      string
	Sent     int64
	Added    int64
}

type Source struct {
	ID          int64
	Url         string
	Name        string
	Config      string
	LastVisited int64
	Retries     int64
}

type Timestamp struct {
	Timestamp int64
}
