version: "3.8"
services:
  # Браузер для рендеринга динамических страниц
  chrome:
    image: "chromedp/headless-shell:74.0.3717.1"
    ports:
      - "9223:9222"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
