version: "3.8"
services:
  # Браузер для рендеринга динамических страниц
  chrome:
    image: "chromedp/headless-shell:74.0.3717.1"
    ports:
      - "9223:9223"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    command:
      - /headless-shell/headless-shell
      - --no-sandbox
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9223
      - --disable-gpu
      - --headless
      - --use-gl=angle
      - --use-angle=swiftshader
      - --disable-dev-shm-usage
      - --enable-logging=stderr
      - --v=1
      - --hide-scrollbars
      - --mute-audio
      - --blink-settings=imagesEnabled=false

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./config:/config
      - ./storage:/storage
    restart: unless-stopped
    command:
      - "/app/parser"
      - "-database"
      - "/storage/database.sqlite3"
     
