sources:
  - name: Dropbox infra
    url: https://dropbox.tech/infrastructure
    config:
      article: ul.dr-article-section__list li
      title: h3 a span
      detail: h3 a
      channels: [tech_blogs_infra]
  - name: Dropbox security
    url: https://dropbox.tech/security
    config:
      article: ul.dr-article-section__list li
      title: h3 a span
      detail: h3 a
      channels: [tech_blogs_sec]
  - name: Dropbox engineering
    url: https://dropbox.tech/application
    config:
      article: ul.dr-article-section__list li
      title: h3 a span
      detail: h3 a
      channels: [tech_blogs_eng]
  - name: Cockroach engineering
    url: https://www.cockroachlabs.com/blog/engineering/
    config:
      article: div.post
      title: h2.card-title
      detail: a
      channels: [tech_blogs_eng]
  - name: Booking engineering
    url: https://blog.booking.com/#development
    config:
      article: div.card-wrap
      title: h4.card__title
      detail: a
      channels: [tech_blogs_eng]
  - name: Booking infra
    url: https://blog.booking.com/#infrastructure
    config:
      article: div.card-wrap
      title: h4.card__title
      detail: a
      channels: [tech_blogs_infra]
  - name: High Scalability
    url: http://highscalability.com/
    config:
      article: div.journal-entry-wrapper
      title: div.journal-entry-text h2 a
      detail: div.journal-entry-text h2 a
      channels: [tech_blogs_arch]
  - name: Mathias Lafeldt
    url: https://sharpend.io/archives/
    config:
      article: article
      title: a
      detail: a
  - name: Applied Go
    url: https://appliedgo.com/blog
    config:
      article: div.zbv-blog-04-content
      title: a:nth-child(2) h3
      detail: a:nth-child(2)
      channels: [tech_blogs_go]
  - name: Jajal Doang
    url: https://www.jajaldoang.com/tags/go/
    config:
      article: article.post-preview
      title: h2.post-title
      detail: a
      channels: [tech_blogs_go]
  - name: The Go Blog
    url: https://go.dev/blog/
    config:
      article: p.blogtitle
      title: a
      detail: a
      tags: [go]
      channels: [tech_blogs_go]
  - name: Bitfield consulting
    url: https://bitfieldconsulting.com/golang/
    config:
      article: article.entry
      title: h2 a
      detail: h2 a
      channels: [tech_blogs_go]
  - name: Alex Edwards
    url: https://www.alexedwards.net/blog
    config:
      article: ol.articles li
      title: a
      detail: a
      channels: [tech_blogs_go]
  - name: Simon Frey
    url: https://simon-frey.com/blog/category/golang/
    config:
      article: article.post
      title: h2.entry-title a
      detail: h2.entry-title a
      channels: [tech_blogs_go]
  - name: Eli Bendersky
    url: https://eli.thegreenplace.net/tag/go
    config:
      article: table.archive-list tbody tr td
      title: a
      detail: a
      channels: [tech_blogs_go]
  - name: Habr Go
    url: https://habr.com/ru/hubs/go/articles/
    config:
      article: div.tm-articles-list article
      title: h2.tm-title a
      detail: h2.tm-title a
      channels: [tech_blogs_go]
  - name: Phill Eaton
    url: https://notes.eatonphil.com/tags/go.html
    config:
      article: div.container div.summary
      title: a
      detail: a
      channels: [tech_blogs_go]
  - name: Ardanlabs
    url: https://www.ardanlabs.com/blog/
    config:
      article: div.post-teaser
      title: header > h1 > a.post-link
      detail: header > h1 > a.post-link
      channels: [tech_blogs_go]
  - name: Dave Cheney
    url: https://dave.cheney.net/
    config:
      article: article.post
      title: header > h1 > a
      detail: header > h1 > a
      channels: [tech_blogs_go]
  - name: Three Dots Labs
    url: https://threedots.tech
    config:
      article: article.post-entry
      title: header.post-header > h3.post-title a
      detail: header.post-header > h3.post-title a
      channels: [tech_blogs_go]
  - name: AWS Architecture
    url: https://aws.amazon.com/ru/blogs/architecture/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
      channels: [tech_blogs_arch]
  - name: AWS OpenSource
    url: https://aws.amazon.com/ru/blogs/opensource/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
      channels: [tech_blogs_eng]
  - name: AWS ML
    url: https://aws.amazon.com/ru/blogs/machine-learning/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
      channels: [tech_blogs_ml]
  - name: AWS DevOps
    url: https://aws.amazon.com/ru/blogs/devops/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
      channels: [tech_blogs_devops]
  - name: AWS Devtools
    url: https://aws.amazon.com/ru/blogs/developer/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
      channels: [tech_blogs_eng]
  - name: Instagram Engineering
    url: https://engineering.fb.com/tag/instagram/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
      channels: [tech_blogs_eng]
  - name: Facebook core infra
    url: https://engineering.fb.com/category/core-infra/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
      channels: [tech_blogs_infra]
  - name: Facebook data infra
    url: https://engineering.fb.com/category/data-infrastructure/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
      channels: [tech_blogs_infra]
  - name: Facebook devtools
    url: https://engineering.fb.com/category/developer-tools/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
      channels: [tech_blogs_eng]
  - name: Facebook production engineering
    url: https://engineering.fb.com/category/production-engineering/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
      channels: [tech_blogs_eng]
  - name: Facebook Security
    url: https://engineering.fb.com/category/security/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
      channels: [tech_blogs_sec]
  - name: Allegro
    url: https://blog.allegro.tech/
    config:
      article: article
      title: a.post-link
      detail: a.post-link
      channels: [tech_blogs_eng]
  - name: Airbnb
    url: https://medium.com/airbnb-engineering
    config:
      article: div.row > div.col > div.col
      title: a > h3 > div
      detail: a
      channels: [tech_blogs_eng]
