sources:
  - name: AWS Architecture
    url: https://aws.amazon.com/ru/blogs/architecture/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
  - name: AWS OpenSource
    url: https://aws.amazon.com/ru/blogs/opensource/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
  - name: AWS ML
    url: https://aws.amazon.com/ru/blogs/machine-learning/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
  - name: AWS DevOps
    url: https://aws.amazon.com/ru/blogs/devops/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
  - name: AWS Devtools
    url: https://aws.amazon.com/ru/blogs/developer/
    config:
      article: article.blog-post
      title: h2.blog-post-title a span
      detail: h2.blog-post-title a
  - name: Three Dots Labs
    url: https://threedots.tech
    config:
      article: article.post-entry
      title: header.post-header > h3.post-title a
      detail: header.post-header > h3.post-title a
  - name: Instagram Engineering
    url: https://engineering.fb.com/tag/instagram/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
  - name: Facebook core infra
    url: https://engineering.fb.com/category/core-infra/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
  - name: Facebook data infra
    url: https://engineering.fb.com/category/data-infrastructure/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
  - name: Facebook devtools
    url: https://engineering.fb.com/category/developer-tools/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
  - name: Facebook production engineering
    url: https://engineering.fb.com/category/production-engineering/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
  - name: Facebook Security
    url: https://engineering.fb.com/category/security/
    config:
      article: article.post
      title: a
      detail: header.entry-header div.entry-title a
  - name: Allegro
    url: https://blog.allegro.tech/
    config:
      article: article
      title: a.post-link
      detail: a.post-link
  - name: Airbnb
    url: https://medium.com/airbnb-engineering
    config:
      article: div.row > div.col > div.col
      title: a > h3 > div
      detail: a
  - name: Ardanlabs
    url: https://www.ardanlabs.com/blog/
    config:
      article: div.post-teaser
      title: header > h1 > a.post-link
      detail: header > h1 > a.post-link